services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: telegram_bot
      POSTGRES_USER: bot_db_user
      POSTGRES_PASSWORD: bot_db_password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bot_db_user -d telegram_bot"]
      interval: 5s
      retries: 5
      timeout: 3s

  bot:
    build: .
    container_name: telegram_bot
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 10s
      retries: 3
      timeout: 5s

volumes:
  pg_data: